# Variables and coefficients
alpha: 20
b: -0.333333
phi0: 0.25
phi_var: 0.004

# Simulation parameters
dt: 0.005
nsteps: 1
iterations: 10000

# dimension: 2 for 2D grid, 3 for Gmsh2DIn3DSpace
dim: 2

# 2D Grid inputs:
nx: 100
ny: 100
dx: 1
dy: 1

# 3D input files
mesh_file: "mesh.geo" # contains inputs for Gmsh2DIn3DSpace

# outputs
log_file: "pfc.log"
trajectory_file: "pfc.h5"
trajectory_write_interval: 1 # in number of steps
