# Variables and coefficients
alpha: 20
b: -0.333333
phi0: 0.25
phi_var: 0.004

# Simulation parameters
dt: 0.005
nsteps: 5
iterations: 10000 # used by pyamgx solver for better convergence

# inputs
mesh_file: "mesh.geo"

# outputs
log_file: "pfc.log"
trajectory_file: "pfc.h5"
trajectory_write_interval: 1 # in number of steps
